# Generated by Django 4.1.1 on 2022-10-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION_VEHICULOS', '0002_vehiculo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometros',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
